name: First workflow

on:
  workflow_dispatch:
    
jobs:
  first_workflow: 
    runs-on: ubuntu-latest
    steps:
      - name: First workflow
        run: |
          echo "Congratulation on First workflow"
